import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import useFetchDB from './useFetchDB';

export default function Home() {

  const { allBlog } = useFetchDB('blogList')

  return (
    <main className={styles.container}>

      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-14">
        <h1 className="text-3xl font-bold text-red-400 text-center pt-8">
          👋 Welcome to tech blog... 📐
        </h1>

        <div className='w-1/2 mx-auto'>
          <h2 className="text-3xl font-bold pt-8 pb-4">Blog Post - </h2>
          <div className='space-y-6'>
            {
              allBlog.map(blog => (
                <Link href={`./blogPost/${blog.slug}`} key={blog.title}>
                  <a className="text-2xl text-red-500 block">{blog.title}</a>
                </Link>
              ))
            }
          </div>
        </div>
      </div>
    </main>
  )
}
