import Head from 'next/head'
import Link from 'next/link'
// import useFetchDB from './useFetchDB';
import * as fs from 'fs';


export default function Home({allBlog}) {

  // const { allBlog } = useFetchDB('blogList');

  return (
    <main>

      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mt-14">
        <h1 className="text-3xl font-bold text-red-400 text-center pt-8">
          👋 Welcome to tech blog... 📐
        </h1>

        <div className='w-1/2 mx-auto'>
          <h2 className="text-3xl font-bold pt-8 pb-4">Blog Post - </h2>
          <div className='space-y-6'>
            {
              allBlog.map(blog => (
                <Link href={`./blogPost/${blog.slug}`} key={blog.title}>
                  <a className="text-2xl text-red-500 block">{blog.title}</a>
                </Link>
              ))
            }
          </div>
        </div>
      </div>
    </main>
  )
}


// SSG ==> Static Site Generation...
export async function getStaticProps(context) {

  let data = await fs.promises.readdir('blogJsonDB');

  let blog;
  let allBlog = [];

  for (let i = 0; i < data.length; i++) {
    const singlePost = data[i];
    blog = await fs.promises.readFile(('blogJsonDB/' + singlePost), 'utf-8');
    allBlog.push(JSON.parse(blog));
  }
  
  return {
    props: { allBlog }
  }

}
